name: abandonedplaces
favicon: null
layout_spectrum: 0.3188864956609905
typography_spectrum: 0.9375047772191465
title: Abandoned Places
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.026406189426779747
  lightness: 0.6266641202382743
  saturation: 0.024161773268133402
  rhythmicContrast: 0.5528959026560187
purpose: []
